project:
  type: website
  output-dir: docs

website:
  title: "Camila Pacheco-Riaño"
  description: "The personal website of Camila Pacheco-Riaño"
  favicon: "media/squirrel.svg"
  google-analytics: "G-JCLT9R2DEK"
  repo-url: https://github.com/Lacapary/Lacapary.github.io
  page-navigation: true
  search: true
  page-footer:
    center:
      - text: "<br>Site made with <i class='bi bi-heart-fill'></i>, <a href='https://github.com/Lacapary/Lacapary.github.io' target='_blank'><i class='bi bi-git'></i></a>, and <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a><br>© 2024 Camila Pacheco-Riaño"
  
  navbar:
    background: '#124f64'
    logo: media/squirrel_t.svg
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Outreach"
        href: Outreach.qmd
      - text: "Collaborate"
        href: collaborate.qmd
        
    tools:
      - icon: twitter-x
        href: https://www.twitter.com/lacapary
      - icon: envelope-at-fill
        href: mailto:pachecoriano.c@gmail.com
      - icon: chat-right-dots-fill
        href: https://bsky.app/profile/lacapary.bsky.social
      - icon: mortarboard-fill
        href: https://www.gu.se/en/about/find-staff/camilapachecoriano
      - icon: github
        href: https://github.com/lacapary

highlight-style: a11y

format:
  html:
    toc: true
    theme: 
      light: [simplex, css/custom.scss]
      dark: [simplex, css/dark.scss, css/custom.scss]
    smooth-scroll: true
    code-overflow: wrap
    include-after-body: mountains.html

execute: 
  echo: false

  